### ISSUE TITLE
Remove cloudflare/wildebeest?

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest-tests-fediverse#101]
The account in the node definition doesn't exist: `acct:gargron@cloudflare.social`.

The only active account that appears to exist on that instance just posted that it moved to Mastodon: https://cloudflare.social/@radar/2338f7ae-6170-4cd4-96f5-0dccfcf05db4/

We need to either find an active account, a different Wildebeest instance, or drop Wildebeest from our list of applications to test.

**Comment by jernst** [comment]
See #103

**Comment by steve-bate** [comment]
Closed since related PR was merged.
