### ISSUE TITLE
Create test that fails type=template in JRD link

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest-tests-fediverse#109]
Per discussion in #105.

**Comment by steve-bate** [comment]
In the current tests, I see:

```json
                {
                    "plan_test_index": 2,
                    "started": "2024-06-06T12:54:23.080073Z",
                    "ended": "2024-06-06T12:54:23.189560Z",
                    "result": {
                        "type": "HardAssertionFailure",
                        "problem_category": "hard",
                        "stacktrace": [
...
                            [
                                "tests/webfinger/server/4_2__2_perform_query.py",
                                19
                            ],
...
                        ],
                        "msg": "Link type not a valid media type: \"template\"\nAccessed URI: \"https://realize.be/.well-known/webfinger?resource=acct%3Aswentel%40realize.be\".\nExpected: None\n     but: was <Link type not a valid media type: \"template\">\n"
                    },
                    "run_steps": null
                },
```

 This is the one I suggested should be a soft fail.

**Comment by jernst** [comment]
I misunderstood? We have a test that fails ... it's just that you think it should be downgraded?

If you feel strongly about it, let's do that, but it seems from the discussion that they really didn't mean it and really should fix it, there is no good reason for it. We don't really want others to start implementing the same pattern because it is sort of okay ...

**Comment by steve-bate** [comment]
I'm not suggesting an endorsement of the pattern (it would still be a failure), but that it doesn't represent an interop risk (which I'm currently interpreting as "soft failure").
