### ISSUE TITLE
Test `Create` with hashtag

### ISSUE THREAD

**Issue by snarfed** [fediverse-devnet/feditest-tests-fediverse#26]
Deliver a `Create` of a `Note` with a tag. Check that the `Note` is visible in search results for the given tag's text. (This is not specified by AP.)

**Comment by snarfed** [comment]
Good question! I only mentioned search as a way to check that the hashtag was handled correctly. How to check that may vary from project to project, ie some may render hashtags specially, some may not, some may support hashtag search, some may not. Up to you!

**Comment by jernst** [comment]
I'm going to call this feature creep and close for now.
