### ISSUE TITLE
Instance actor should not be a Person

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest-tests-fediverse#52]
Threads apparently says it is a Person, see https://threads.net/ap/users/threads.sys

**Comment by steve-bate** [comment]
I don't know of any requirement for an "instance actor" to not be a `Person` type. The whole concept is outside the scope of AP. I don't know of any federation or interop requirements for it other than for working around the Mastodon authorized fetch design. Even then, *any* actor in that instance not requiring an HTTP signature can be used for that, so an "instance actor" is not necessarily required for that purpose.
