### ISSUE TITLE
More WebFinger servers

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest-tests-fediverse#72]
[servers.json](https://github.com/fediverse-devnet/feditest-tests-fediverse/files/15287266/servers.json)

Added more WebFinger implementation hostname/accounts (34 total).

**Comment by jernst** [comment]
Do we need more than one account per software package? I would propose not, so I'm not adding:

>        "hostname": "pleroma.makemake.site",
>         "account": "makemake",

>         "hostname": "writefreely.pl",
>         "account": "kierunkowy74",

>         "hostname": "owncast.small-web.org",
>         "account": "fedi",

>         "hostname": "social.funkwhale.audio",
>         "account": "funkwhale",

>         "hostname": "hub.hubzilla.de",
>         "account": "funbreaker",

>         "hostname": "plume.pullopen.xyz",
>         "account": "amanda",

    # TODO Can't find account
    # {
    #     "constellation_name": "NextCloud",
    #     "hostname" : "cloud.speicherbereich.net",
    #      "account" : "...",
    # },

We can run it locally under UBOS: https://github.com/fediverse-devnet/feditest/issues/113

**Comment by steve-bate** [comment]
Closing, assuming these are included in #77.
